# ======================================================
#          SPECIAL SMP - OFFICIAL CONFIGURATION
# ======================================================

# --- CORE SETTINGS ---
settings:
  show-cooldown-actionbar: true
  no-permission-msg: "&c&l[!] &7Insufficient permissions!"

# --- CARD COOLDOWNS (In Seconds) ---
cooldowns:
  "Enderman Card":
    left: 60
    right: 40
    shift_right: 90
  "Herobrine Card":
    left: 10
    right: 60
    shift_right: 180
  "Zombie Card":
    left: 60
    right: 60
    shift_right: 120
  "Creeper Card":
    left: 60
    right: 90
    shift_right: 120
  "Lighting Card":
    left: 40
    right: 20
    shift_right: 60
  "Poseidon Card":
    left: 30
    right: 60
    shift_right: 120
  "Warden Card":
    left: 60
    right: 120
    shift_right: 180
  "Ghost Card":
    left: 60
    right: 40
    shift_right: 90
  "Ruin Card":
    left: 30
    right: 45
    shift_right: 60
  "Nothing Card":
    left: 20
    right: 40
    shift_right: 60
  "Ultimate Card":
    left: 120
    right: 120
    shift_right: 300

# --- CARD SPECIFIC SETTINGS ---
settings-extra:
  zombie:
    max-zombies: 2
    duration: 60
  illusionist:
    clone-duration: 10

# --- SMP START SYSTEM ---
smp-start-system:
  enabled: false
  starter-name: "THE SERVER ARCHITECT"
  border:
    initial-size: 5.0
    final-size: 1000.0
    expansion-duration: 15
  timers:
    countdown-delay: 300
    item-distribution-delay: 600
  messages:
    countdown-title: "§c§l%time%"
    countdown-subtitle: "§7The World is Tearing Apart..."
    startup-title: "§6§lSMP INITIATED"
    startup-subtitle: "§fStarted By: §b%starter%"
    fate-warning-title: "§e§lFATE ARRIVING IN"
    fate-warning-subtitle: "§6%time%..."
    fate-grant-title: "§b§lFATE SYNCHRONIZED"
    fate-grant-subtitle: "§fStarter Fate Kit Distributed!"

# --- STARTER POOL ---
allowed-first-join-cards:
  - "Enderman Card"
  - "Herobrine Card"
  - "Nothing Card"
  - "Zombie Card"
  - "Warden Card"
  - "Creeper Card"
  - "Lighting Card"
  - "Ghost Card"
  - "Ruin Card"
  - "Poseidon Card"
